communicationportal/home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordResetForm
    )
urlpatterns = [
    url(r"login/$", LoginView.as_view(template_name="login.html"), name="login"),
    url(r"logout/$", LogoutView.as_view(template_name="logout.html"), name="logout"),
    url(r"reset-password/$", PasswordResetView.as_view(),name="reset_password"),
    url(r"reset-password/done/$", PasswordResetDoneView.as_view(),name="password_reset_done"),
    url(r"reset-password/complete/$", PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    url(r"reset-password/confirm/(?P<uidb64>[0-9a-zA-Z]+)-(?P<token>.+)/$", PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    url(r"home/$", views.home, name="home"),    
    url(r"videos/add/$", views.add_videos,name="add_videos"),
    url(r"products/add/$", views.add_products,name="add_products"),
    url(r"products/details/([0-9]+)/$", views.product_details,name="product_details"),
    url(r"products/$", views.products,name="products"),
    url(r"real-estate/add/$", views.add_real_estate,name="add_real_estate"),
    url(r"real-estate/details/([0-9]+)/$", views.real_estate_details,name="real-estate_details"),
    url(r"real-estate/$", views.real_estate,name="real_estate"),
    url(r"videos/$", views.videos,name="videos"),
    url(r"profile/$", views.view_profile,name="view_profile"),
    url(r"profile/edit/$", views.edit_profile,name="edit_profile"),
    url(r"profile/change-password/$", views.change_password,name="change_password"),
    url(r"register/$", views.register,name="register"),
    url(r"profile/chat/$", views.chat_view,name="chat"),
    # url(r"legal/$", views.legal,name="legal"),
    # url(r"category/$", views.category,name="category"),
]

communicationportal/portal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

def login_redirect(request):
    return redirect('/login')

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"", include('home.urls')),    
    url(r"^$", login_redirect, name='login_redirect'),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communicationportal/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
class Member(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=30,default='')
    address = models.CharField(max_length=100,default='')
    email = models.EmailField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image/', blank=True)
    # time = models.DateTimeField(auto_now_add=True)
    # chat = models.FilePathField(path="/portal/media/chat/user2.py",default="hello")
    # models.DateTimeField()
    def __str__(self):
        return self.user.username

class Chat(models.Model):
    # sender = models.OneToOneField(User,on_delete=models.CASCADE)
    sender = models.CharField(max_length=30, default='')
    reciever = models.CharField(max_length=30, default='')
    logged_user = models.CharField(max_length=30, default='')
    time = models.DateTimeField(auto_now=True)
    message = models.CharField(max_length=1000 ,default="")

    def __str__(self):
        return self.sender+" to "+ self.reciever
class Video(models.Model):
    name= models.CharField(max_length=500)
    videofile= models.FileField(upload_to='videos/', null=True, verbose_name="")

    def __str__(self):
        return self.name + ": " + str(self.videofile)


class Product(models.Model):
    name= models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    price = models.IntegerField(default=None)
    image = models.ImageField(upload_to='products/',  null=True, verbose_name="")

    def __str__(self):
        return self.name

class RealEstate(models.Model):
    name= models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    price = models.IntegerField(default=None)
    image = models.ImageField(upload_to='realestate/',  null=True, verbose_name="")

    def __str__(self):
        return self.name

class Legal(models.Model):
    description = models.CharField(max_length=1000000)

    def __str__(self):
        return str("Legal")

def create_profile(sender, **kwags):
    if kwags['created']:
        Member.objects.create(user=kwags['instance'])




post_save.connect(create_profile, sender=User)

# def create_chat(sender, **kwags):
#     if kwags['created']:
#         Chat.objects.create(user=kwags['instance'])

# post_save.connect(create_chat, sender=User)

communicationportal/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm
from .form import RegistrationForm,EditProfileForm,VideoForm,ProductForm,RealEstateForm,LegalForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import update_session_auth_hash
import datetime
from .models import Chat,Member,Video,Product,RealEstate,Legal
from .login_check import logged_user
import re
from django.core.paginator import Paginator

# from .models import 

# @user_passes_test(redirect_field_name='/home')
def login(request):
    return HttpResponseRedirect("/login")

@login_required(login_url='/login')
def home(request):
    return render(request, 'home/home.html')

@login_required(login_url='/login')
def chat_view(request):

    objects = Member.objects.exclude(user_id=request.user.id)
    # admin = Member.objects.filter(id=5)
    # objects = objects.difference(admin)
    if objects:
        obj_ins = objects[0]
    else:
        obj_ins = None

    if request.user.username != "admin":
        chat_objects1 = Chat.objects.filter(sender=request.user, reciever="admin")
        chat_objects2 = Chat.objects.filter(sender="admin", reciever=request.user)
        chat_objects =  (chat_objects1.union(chat_objects2))
        chat_object = logged_user(chat_objects, request.user.username)
        if request.method == "POST":
            
            chat = Chat()
            chat.sender = request.user
            chat.message = request.POST["message"]
            chat.reciever = "admin"
            chat.save()
            chat_objects1 = Chat.objects.filter(sender=request.user, reciever="admin")
            chat_objects2 = Chat.objects.filter(sender="admin", reciever=request.user)
            chat_objects = chat_objects1.union(chat_objects2)
            chat_objects = (chat_objects.order_by("time"))
            chat_objects = logged_user(chat_objects, request.user.username)
            return HttpResponseRedirect("/profile/chat")
        return render(request, 'home/chat.html', {"data": reversed(chat_objects)})
    else:
        if request.method == "POST":
            try:
                reciever = request.POST["user_name"]
                request.session["reciever"] = reciever
                chat_objects1 = Chat.objects.filter(sender=request.user, reciever=reciever)
                chat_objects2 = Chat.objects.filter(sender=reciever, reciever=request.user)
                chat_objects = chat_objects1.union(chat_objects2)
                chat_objects = (chat_objects.order_by("time"))
                chat_objects = logged_user(chat_objects, request.user.username)
                obj_ins_id = User.objects.select_related("member").get(username=reciever)
                obj_ins = Member.objects.filter(user_id=obj_ins_id.id)[0]
                args = { "objects": objects, "data" : reversed(chat_objects), "obj_ins": obj_ins}
                return render(request, 'home/admin_chat.html', args)
            except Exception:
                message = request.POST['message']
                reciever = request.session["reciever"]
                print(reciever)
                chat = Chat()
                chat.sender = request.user
                chat.message = message
                chat.reciever = reciever
                chat.save()
                chat_objects1 = Chat.objects.filter(sender=request.user, reciever=reciever)
                chat_objects2 = Chat.objects.filter(sender=reciever, reciever=request.user)
                chat_objects = chat_objects1.union(chat_objects2)
                chat_objects = (chat_objects.order_by("time"))
                chat_objects = logged_user(chat_objects, request.user.username)
                obj_ins_id = User.objects.select_related("member").get(username=reciever)
                obj_ins = Member.objects.filter(user_id=obj_ins_id.id)[0]
                args = { "objects": objects, "data" : reversed(chat_objects), "obj_ins": obj_ins}
                return render(request, 'home/admin_chat.html', args )
        

        chat_objects1 = Chat.objects.filter(sender=request.user, reciever=obj_ins.user)
        chat_objects2 = Chat.objects.filter(sender=obj_ins.user, reciever=request.user)
        chat_objects =  (chat_objects1.union(chat_objects2))
        chat_object = logged_user(chat_objects, request.user.username)
        print(obj_ins.image.url)
        args = { "objects": objects, "data" : reversed(chat_objects), "obj_ins ": obj_ins}
        return render(request, 'home/admin_chat.html',args)
    
@login_required(login_url='/login')
def products(request):
    products = Product.objects.all()
    paginator = Paginator(products, 6)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    args = {"products": products}
    return render(request, 'home/products.html',args)

@login_required(login_url='/login')
def add_products(request):
    if request.user.username == "admin":
        products = Product.objects.all()
        paginator = Paginator(products, 5)
        page = request.GET.get('page')
        products = paginator.get_page(page)
        args = { "products": products }
        if request.method == "POST":
            for count, x in enumerate(request.FILES.getlist("image")):
                form= ProductForm(request.POST or None, {'image':x})
                if form.is_valid():
                    form.save()
            return HttpResponseRedirect("/products/add/")
        return render(request, 'add_products.html', args)
    else:
        return HttpResponseRedirect("/products/")

@login_required(login_url='/login')
def product_details(request, pk=None):
    try:
        product_id = str(request)
        product_id = re.findall(".+([0-9]+)", product_id)[0]
        product = Product.objects.filter(id=product_id)[0]
        print(product)
        args = {"product" : product}
        return render(request, "home/product_details.html",args)
    except Exception:
        return HttpResponseRedirect("/products/")

@login_required(login_url='/login')
def real_estate(request):
    real_estates = RealEstate.objects.all()
    args = {"real_estates": real_estates}
    return render(request, 'home/real_estate.html',args)

@login_required(login_url='/login')
def add_real_estate(request):
    if request.user.username == "admin":
        real_estates = RealEstate.objects.all()
        args = { "real_estates": real_estates }
        if request.method == "POST":
            form= RealEstateForm(request.POST or None, request.FILES or None)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect("/real-estate/add/")
            else:
                return HttpResponseRedirect("/real-estate/add/")
        return render(request, 'home/add_real_estate.html', args)
    else:
        return HttpResponseRedirect("/real-estate/")

@login_required(login_url='/login')
def real_estate_details(request, pk=None):
    try:
        real_estate_id = str(request)
        real_estate_id = re.findall(".+([0-9]+)", real_estate_id)[0]
        real_estate = RealEstate.objects.filter(id=real_estate_id)[0]
        # print(real_estate)
        args = {"real_estate" : real_estate}
        return render(request, "home/real_estate_details.html",args)
    except Exception:
        return HttpResponseRedirect("/real-estate/")
    
@login_required(login_url='/login')
def videos(request):
    # print("videos")
    videos = Video.objects.all()
    paginator = Paginator(videos, 6)
    page = request.GET.get('page')
    videos = paginator.get_page(page)
    args = { "videos": videos }
    return render(request, 'home/videos.html', args)

@login_required(login_url='/login')
def add_videos(request):
    if request.user.username == "admin":
        videos = Video.objects.all()
        paginator = Paginator(videos, 5)
        page = request.GET.get('page')
        videos = paginator.get_page(page)
        args = { "videos": videos }
        if request.method == "POST":
            for count, x in enumerate(request.FILES.getlist("videofile")):
                form= VideoForm(request.POST or None, {'videofile':x})
                if form.is_valid():
                    form.save()
            return HttpResponseRedirect("/videos/add/")
        return render(request, 'add_videos.html', args)
    else:
        return HttpResponseRedirect("/videos/")
        
def register(request):
    if request.method == 'POST':
        full_name = str(request.POST['first_name']) + str(request.POST['last_name'])
        form = RegistrationForm(request.POST)
        form2 = EditProfileForm(request.POST or None, request.FILES or None)
        if form.is_valid() and form2.is_valid():
            form.save()
            obj_ins_id = User.objects.select_related("member").get(username=request.POST['username'])
            obj_ins = Member.objects.filter(user_id=obj_ins_id.id)[0]
            obj_ins.full_name = full_name
            obj_ins.address = request.POST['address']
            obj_ins.email = request.POST['email']
            obj_ins.image = 'profile_image/'+request.POST['image']
            obj_ins.save()
            return redirect('/home')
        else:
            print(request.POST)
    else:
        form = RegistrationForm()
    args = {'form': form}
    return render(request, 'register.html', args)

@login_required(login_url='/login')
def view_profile(request):
    if request.method == 'POST':    
        return redirect('/logout')
    args = {'user':request.user}
    return render(request, 'home/view_profile.html',args)

@login_required(login_url='/login')
def edit_profile(request):
    if request.method == 'POST':
        # print(request.POST)
        request.user.first_name = request.POST['first_name']
        request.user.last_name = request.POST['last_name']
        request.user.save()      

communicationportal/home/templates/add_products.html
{% extends 'base.html' %}
{% load static %}
<html>
  <head>
    {% block head %}
    <title>Add Products</title>
    {% endblock %}
  </head>
  <body>
    {% block body %}

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="/home"><h2>Communication <em>Portal</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if user.username == "admin" %}
                <li class="nav-item active">
                <a class="nav-link" href="">Add
                </a>
              </li>
              {% endif %} 
              <li class="nav-item">
                <a class="nav-link" href="/home">Home
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="/videos">Videos</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="/products">Products</a>
              </li>
              <!-- <li class="nav-item ">
                <a class="nav-link" href="/real-estate">Real Estate</a>
              </li> -->
              <li class="nav-item">
                <a class="nav-link" href="/profile">Profile</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    <div class=" header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
            </div>
          </div>
        </div>
      </div>
    </div>

    
    <div style="padding-bottom: 30px;" class="products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="filters">
              <ul>
                  <li class="active" data-filter="*">All Products</li>
              </ul>
            </div>
          </div>
          <div class="col-md-12">
            <div class="filters-content">
                <div class="row grid">
                    {% for product in products %}
                    <div class="col-lg-4 col-md-4 all des">
                      <div class="product-item">
                        <a ><img width='350' height="200" src="{{ MEDIA_URL }}{{ product.image }}" alt=""></a>
                        <div class="down-content">
                          <a ><h4>{{product.name}}</h4></a>
                          <h6>${{product.price}}</h6>
                          <p>{{product.description}}</p>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                    <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <div class="col-lg-4 col-md-4 all des">
                      <div class="product-item">
                        <input multiple type="file" name="image" accept="image/*" required id="id_image">
                        <div >
                        <p><input type="text" placeholder="Product Name" name="name" maxlength="50" required id="id_name"></p>
                          <p>$<input type="number" placeholder="Price" name="price" required id="id_price"></p>
                          <p><input type="text" placeholder="Description" name="description" maxlength="500" required id="id_description"></p>
                        </div>
                      </div>
                      <input type="submit" value="Upload"/>
                    </div>
                    </form>
                  </div>
            </div>
          </div>
          <div class="col-md-12">
            <ul class="pages">
              {% if products.has_previous %}
                <li><a href="?page={{products.number|add:'-1'}}"><i class="fa fa-angle-double-left"></i></a></li>
                <li><a href="?page={{products.number|add:'-1'}}">{{products.number|add:'-1'}}</a></li>
              {% endif %}
              <li class="active"><a href="?page={{products.number}}">{{products.number}}</a></li>
              {% if products.has_next %}
                <li><a href="?page={{products.number|add:'1'}}">{{products.number|add:'1'}}</a></li>
                <li><a href="?page={{products.number|add:'1'}}"><i class="fa fa-angle-double-right"></i></a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>

    {% endblock %}


  </body>

</html>

communicationportal/home/templates/add_videos.html
{% extends 'base.html' %}
{% load static %}
<html>
  <head>
    {% block head %}
    <title>Videos</title>
    {% endblock %}
  </head>
  <body>
    {% block body %}

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header >
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="/home"><h2>Communication <em>Portal</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                    {% if user.username == "admin" %}
                    <li class="nav-item">
                    <a class="nav-link active" href="">Add
                    </a>
                    </li> 
                    {% endif %}
                    <li class="nav-item">
                <a class="nav-link" href="/home">Home
                </a>
              </li> 
              <li class="nav-item ">
                <a class="nav-link" href="/videos">Videos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/products">Products</a>
              </li>
              <!-- <li class="nav-item ">
                <a class="nav-link" href="/real-estate">Real Estate</a>
              </li> -->
              <li class="nav-item">
                <a class="nav-link" href="/profile">Profile</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!-- Page Content -->
    <div class=" header-text">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="text-content">
              </div>
            </div>
          </div>
        </div>
      </div>

    
    <div style="padding-bottom: 30px;" class="products">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="filters">
              <ul>
                  <li class="active" data-filter="*">All Videos</li>
              </ul>
            </div>
          </div>
          <div class="col-md-12">
            <div class="filters-content">
                <div class="row grid">
                  {% for video in videos %}
                    <div class="col-lg-4 col-md-4 all des">
                      <div class="product-item">
                        <video width='350' height="200" controls>
                        <source src='{{ MEDIA_URL }}{{ video.videofile }}' type='video/mp4'>
                        Your browser does not support the video tag.
                        </video>
                        <div class="down-content">
                          <a><h4>{{ video.name }}</h4></a>                          
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                  <form enctype="multipart/form-data" method="POST">
                      {% csrf_token %}
                      <div class="col-lg-4 col-md-4 all des">
                      <div class="product-item">
                          <input multiple type="file" name="videofile" required id="id_videofile">
                    <div class="down-content">
                      <p> <input type="text" placeholder="Name" name="name" maxlength="50" required id="id_name"></p>                        
                    </div>
                  </div>
                    <input type="submit" value="Upload"/>
                  </div>
                  </form>
                </div>
            </div>
          </div>
          <div class="col-md-12">
            <ul class="pages">
              {% if videos.has_previous %}
                <li><a href="?page={{videos.number|add:'-1'}}"><i class="fa fa-angle-double-left"></i></a></li>
                <li><a href="?page={{videos.number|add:'-1'}}">{{videos.number|add:'-1'}}</a></li>
              {% endif %}
              <li class="active"><a href="?page={{videos.number}}">{{videos.number}}</a></li>
              {% if videos.has_next %}
                <li><a href="?page={{videos.number|add:'1'}}">{{videos.number|add:'1'}}</a></li>
                <li><a href="?page={{videos.number|add:'1'}}"><i class="fa fa-angle-double-right"></i></a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script></html>
    {% endblock %}

  </body>

</html>

communicationportal/home/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Register</title>
<style>
  body {
          margin: 0;
          padding: 0;
          height: 100vh;
        }
        #login .container #login-row #login-column #login-box {
          margin-top: 120px;
          max-width: 600px;
          height: 1000px;
          border: 1px solid #9C9C9C;
          background-color: #EAEAEA;
        }
        #login .container #login-row #login-column #login-box #login-form {
          padding: 20px;
        }
        #login .container #login-row #login-column #login-box #login-form #register-link {
          margin-top: -85px;
        }
  .pass_para{
    color: rosybrown;
    font-size: .8rem;
  }
</style>
{% endblock %}


{% block body %}
    <div>
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="/home" ><h2> <em>Register</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="/login">Log In</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  </div>
  <div id="login">
    <h3 class="text-center text-white pt-5">Login form</h3>
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6">
                <div id="login-box" class="col-md-12">
                    <form id="login-form" class="form" action="" method="post">
                      {% csrf_token %}
                        <h3 class="text-center text-info">Register</h3>
                        <div class="form-group">
                            <label class="text-info" for="id_username">Username:</label><br>
                            <input type="text" name="username" maxlength="150" autofocus required id="id_username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="id_first_name">First name:</label><br>
                            <input type="text" name="first_name" required maxlength="150" id="id_first_name"class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="id_last_name">Las name:</label><br>
                            <input type="text" name="last_name" maxlength="150" id="id_last_name"class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="id_email">Email address:</label><br>
                            <input type="email" name="email" required maxlength="254" id="id_email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="id_password1">Password:</label><br>
                            <input type="password" name="password1" autocomplete="new-password" required id="id_password1" class="form-control">
                            <ul class = "pass_para">
                              <li>Your password can’t be too similar to your other personal information.</li>
                              <li>Your password must contain at least 8 characters.</li>
                              <li>Your password can’t be a commonly used password.</li>
                              <li>Your password can’t be entirely numeric.</li>
                            </ul>
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="id_password2">Password confirmation:</label><br>
                            <input type="password" name="password2" autocomplete="new-password" required id="id_password2" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="id_address">Address:</label><br>
                            <input type="text" name="address" maxlength="100" required id="id_address" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="id_phone">Phone:</label><br>
                            <input type="number" name="phone" value="" required id="id_phone" class="form-control">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="id_image">Profile Photo</label><br>
                            <input type="file" name="image" required accept="image/*" id="id_image" >
                        </div>
                        <div class="form-group">
                            <label for="remember-me" class="text-info"><span></span> <span></span></label><br>
                            <input type="submit" name="submit" class="btn btn-info btn-md" value="Submit">
                        </div>
                        </div>
                    </form>
                    <!-- <form method="POST">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <button type="submit" class="btn">Submit</button>
                    </form> -->
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- <div class="container" style="padding-top: 100px;">
      <a class="navbar-brand"><h1><em>Register</em></h1></a>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Submit</button>
      </form>
    </div> -->
{% endblock %}